// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	job "job-queue/internal/domain/job"

	mock "github.com/stretchr/testify/mock"
)

// JobGet is an autogenerated mock type for the JobGet type
type JobGet struct {
	mock.Mock
}

// GetJob provides a mock function with given fields: ctx, jobID
func (_m *JobGet) GetJob(ctx context.Context, jobID int) (job.Job, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJob")
	}

	var r0 job.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (job.Job, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) job.Job); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Get(0).(job.Job)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJobGet creates a new instance of JobGet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobGet(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobGet {
	mock := &JobGet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
