// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	postgres "job-queue/internal/repository/postgres"

	mock "github.com/stretchr/testify/mock"
)

// JobGet is an autogenerated mock type for the JobGet type
type JobGet struct {
	mock.Mock
}

// GetJob provides a mock function with given fields: jobID
func (_m *JobGet) GetJob(jobID int) (postgres.Job, error) {
	ret := _m.Called(jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJob")
	}

	var r0 postgres.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (postgres.Job, error)); ok {
		return rf(jobID)
	}
	if rf, ok := ret.Get(0).(func(int) postgres.Job); ok {
		r0 = rf(jobID)
	} else {
		r0 = ret.Get(0).(postgres.Job)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJobGet creates a new instance of JobGet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobGet(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobGet {
	mock := &JobGet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
