// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	json "encoding/json"
	job "job-queue/internal/domain/job"

	mock "github.com/stretchr/testify/mock"

	models "job-queue/internal/models"
)

// JobSaver is an autogenerated mock type for the JobSaver type
type JobSaver struct {
	mock.Mock
}

// SaveJob provides a mock function with given fields: ctx, queue, payload
func (_m *JobSaver) SaveJob(ctx context.Context, queue models.QueueType, payload json.RawMessage) (job.Job, error) {
	ret := _m.Called(ctx, queue, payload)

	if len(ret) == 0 {
		panic("no return value specified for SaveJob")
	}

	var r0 job.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.QueueType, json.RawMessage) (job.Job, error)); ok {
		return rf(ctx, queue, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.QueueType, json.RawMessage) job.Job); ok {
		r0 = rf(ctx, queue, payload)
	} else {
		r0 = ret.Get(0).(job.Job)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.QueueType, json.RawMessage) error); ok {
		r1 = rf(ctx, queue, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJobSaver creates a new instance of JobSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobSaver {
	mock := &JobSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
