// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	json "encoding/json"
	postgres "job-queue/internal/repository/postgres"

	mock "github.com/stretchr/testify/mock"
)

// JobSaver is an autogenerated mock type for the JobSaver type
type JobSaver struct {
	mock.Mock
}

// SaveJob provides a mock function with given fields: queue, payload
func (_m *JobSaver) SaveJob(queue postgres.QueueType, payload json.RawMessage) (postgres.Job, error) {
	ret := _m.Called(queue, payload)

	if len(ret) == 0 {
		panic("no return value specified for SaveJob")
	}

	var r0 postgres.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(postgres.QueueType, json.RawMessage) (postgres.Job, error)); ok {
		return rf(queue, payload)
	}
	if rf, ok := ret.Get(0).(func(postgres.QueueType, json.RawMessage) postgres.Job); ok {
		r0 = rf(queue, payload)
	} else {
		r0 = ret.Get(0).(postgres.Job)
	}

	if rf, ok := ret.Get(1).(func(postgres.QueueType, json.RawMessage) error); ok {
		r1 = rf(queue, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJobSaver creates a new instance of JobSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobSaver {
	mock := &JobSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
