// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// JobDelete is an autogenerated mock type for the JobDelete type
type JobDelete struct {
	mock.Mock
}

// DeleteJob provides a mock function with given fields: ctx, jobID
func (_m *JobDelete) DeleteJob(ctx context.Context, jobID int) error {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJobDelete creates a new instance of JobDelete. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobDelete(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobDelete {
	mock := &JobDelete{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
