// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	postgres "job-queue/internal/repository/postgres"

	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// ChangeStatus provides a mock function with given fields: id, status
func (_m *Storage) ChangeStatus(id int64, status postgres.JobStatus) error {
	ret := _m.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for ChangeStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, postgres.JobStatus) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchPendingJobs provides a mock function with no fields
func (_m *Storage) FetchPendingJobs() ([]postgres.Job, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchPendingJobs")
	}

	var r0 []postgres.Job
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]postgres.Job, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []postgres.Job); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]postgres.Job)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
