// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	job "job-queue/internal/domain/job"

	mock "github.com/stretchr/testify/mock"

	models "job-queue/internal/models"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// ChangeStatus provides a mock function with given fields: ctx, jobID, status
func (_m *Storage) ChangeStatus(ctx context.Context, jobID int64, status models.JobStatus) error {
	ret := _m.Called(ctx, jobID, status)

	if len(ret) == 0 {
		panic("no return value specified for ChangeStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.JobStatus) error); ok {
		r0 = rf(ctx, jobID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchPendingJobs provides a mock function with given fields: ctx
func (_m *Storage) FetchPendingJobs(ctx context.Context) ([]job.Job, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchPendingJobs")
	}

	var r0 []job.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]job.Job, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []job.Job); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]job.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
